### ISSUE TITLE
[WeiDU] Object parameters should use a distinct color in .baf/.d files

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#1]
If I write `CheckSpellState(Myself,BERSERKER_RAGE)`, both the _trigger_ and the _object reference_ are highlighted with the same color.

It would be (much) better to have two distinct colors.........

**Comment by burner1024** [comment]
1. See [this](https://forum.bgforge.net/viewtopic.php?f=35&t=139) for suggestions about highlighting.
2. It's best to include a screenshot.
3. Easier said than done, anyway. Don't know which theme do you use, but all colors in Monokai are already used up.
I think I'll change identifiers scope to constant (which they are), but that still won't allow to distinguish between objects and other ids.
If you have an actual suggestion, feel free to voice it.

**Comment by 4Luke4** [comment]
> Don't know which theme do you use, but all colors in Monokai are already used up.

I was using **Solarized Dark**. I fixed the issue via changing the Color Theme (as you suggested). Maybe this issue only affects certain Color Themes......

**Comment by burner1024** [comment]
I didn't suggest that. And it appears I misunderstood the issue. (that's where a screenshot would help).
Anyway, if everything's good for you, I'll close this for now.

**Comment by 4Luke4** [comment]
> (that's where a screenshot would help).

Here it is.
<img width="915" alt="same color" src="https://user-images.githubusercontent.com/39967126/50551734-e98c9900-0c85-11e9-83df-a6312930c7df.png">

**Comment by burner1024** [comment]
Indeed, that's more of a theme problem. And I see that actions are colored the same as triggers in it, anyway.
Unfortunately, it's not possible to cater to all themes, as they often contradict each other. For now, I'm only targeting Monokai.
