### ISSUE TITLE
Weird behavior when using "" or ~~

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#13]
Let's consider the following example:
```
LAF DELETE_SCRIPT_BLOCK
STR_VAR
	script = ~GTSUM00~
	match = EVAL "RESPONSE #100[%WNL%%LNL%%MNL%]*END"
END
```

All the code that follows this line `match = EVAL "RESPONSE #100[%WNL%%LNL%%MNL%]*END"` is highlighted in yellow (as if a string delimiter is missing).

Why!?
<img width="940" alt="Missing string delimiter ?" src="https://user-images.githubusercontent.com/39967126/63652067-63651b80-c75c-11e9-83dc-4beedcc3f661.png">

**Comment by burner1024** [comment]
Quite clear when you look at it, LAF find END and stops there, everything after that is separated, and the quotes open a new string.
I'm not sure how to fix this, though. Need a clear indication that LAF invocation is over.

**Comment by 4Luke4** [comment]
> I'm not sure how to fix this, though. Need a clear indication that LAF invocation is over.

Guess you should ignore `END` if it's part of a string......

**Comment by burner1024** [comment]
> Guess `END` should not qualify as the end of a function invocation if it's included in a string (i.e., if it's between two `""` or `~~`......)

Yeah, only that needs to be in [regex terms](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/dfb53b9d9d604d068380e842f3e987564659be12/syntaxes/weidu.tmLanguage.yml#L623).

**Comment by burner1024** [comment]
Here's a [try](https://regex101.com/r/CWXHOH/1)... works on the site but not in VScode for some reason. And I don't like how it's 428 steps, anyway.

**Comment by 4Luke4** [comment]
@burner1024 

We must find a solution in any case because this issue is quite annoying IMHO...

**Comment by burner1024** [comment]
I'm open to suggestions.

**Comment by burner1024** [comment]
Probably can color it individually instead of trying to parse the entire invocation. It'll likely bite back at some time, but I don't really see a better option.

**Comment by 4Luke4** [comment]
> Probably can color it individually instead of trying to parse the entire invocation. It'll likely bite back at some time, but I don't really see a better option.

Could you provide a screenshot?

**Comment by burner1024** [comment]
It means that it'll likely break again in some other edge cases, and that won't be easily fixable.
The core problem is that weidu treats all whitespace the same, while tmlanguage syntax doesn't (specifically, newlines).

**Comment by 4Luke4** [comment]
@burner1024 

What about opening a [feature request](https://github.com/WeiDUorg/weidu/issues) then?

**Comment by burner1024** [comment]
About what?

**Comment by 4Luke4** [comment]
> About what?

About treating **newlines** differently from the other whitespace characters (space, TAB and so forth...)

**Comment by burner1024** [comment]
That's impossible, it'll break half the mods.

**Comment by burner1024** [comment]
And just about the same can be accomplished by modders themselves.

**Comment by burner1024** [comment]
Huh? Doesn't show that for me. "Launch client", I think.

**Comment by 4Luke4** [comment]
> Huh? Doesn't show that for me. "Launch client", I think.

OK, I'm done.

Unfortunately, now issues occur when the name of a function is a `%variable%` (have a look at the attached screenshot)

<img width="840" alt="LPF %variable%" src="https://user-images.githubusercontent.com/39967126/64851165-22ec1580-d617-11e9-9a7b-1e1179bfeec0.png">

**Comment by burner1024** [comment]
Function name as a variable?! What kind of witchery is this??

Please drop the snippets as text, so I could test.

**Comment by 4Luke4** [comment]
> Function name as a variable?! What kind of witchery is this??

As you probably know, WeiDU's built-in functions (`REPLACE_BCS_BLOCK`, search & replace, etc...) are not very reliable when it comes to editing existing scripts.

As a result, [DavidW](https://www.gibberlings3.net/profile/1067-davidw/) wrote down a series of BCS-editing functions in order to solve that issue. You can find them [here](https://github.com/Gibberlings3/SwordCoastStratagems/blob/master/stratagems/lib/alter_script.tpa).

**Comment by burner1024** [comment]
It was a rethorical question. Anyway, I still need the snippets.

**Comment by 4Luke4** [comment]
> It was a rethorical question. Anyway, I still need the snippets.

What do you mean by _"snippets"_?

I've already sent you a link to the functions in question.....

**Comment by burner1024** [comment]
The code that you're having problems with, as text.

**Comment by 4Luke4** [comment]
> The code that you're having problems with, as text.

OK, here you go (do you have problems with copy & paste)?

<details>
  <summary>Spoiler warning</summary>

```
DEFINE_ACTION_FUNCTION internal_script_block_master
INT_VAR insert_above=0
        only_once=0
        recompile=1
        replace=0
STR_VAR script=""
        patch=""
        patch_original=""
        match_function=""
        match=""
        match1=""
        match2=""
        match3=""
        match4=""
        match5=""
        internal_type=""
        internal_insert_data=""
        swap_out=""
        swap_out1=""
        swap_out2=""
        swap_out3=""
        swap_out4=""
        swap_out5=""
        swap_in=""
        swap_in1=""
        swap_in2=""
        swap_in3=""
        swap_in4=""
        swap_in5=""
        original_swap_out=""
        original_swap_out1=""
        original_swap_out2=""
        original_swap_out3=""
        original_swap_out4=""
        original_swap_out5=""
        original_swap_in=""
        original_swap_in1=""
        original_swap_in2=""
        original_swap_in3=""
        original_swap_in4=""
        original_swap_in5=""
BEGIN
COPY_EXISTING "%script%.bcs" "override"
     SET found_match=0
     SPRINT new_script ""
     SET start=INDEX_BUFFER("CR")
     WHILE start>0 BEGIN
          SET end=INDEX_BUFFER ("RS%LNL%CR%LNL%")
          SET length=(end - start) + 6
          READ_ASCII start data (length)
          DELETE_BYTES start length
          INNER_PATCH_SAVE data "SC%LNL%%data%SC%LNL%" BEGIN
             DECOMPILE_BCS_TO_BAF
             SET proceed=0
             PATCH_IF (!found_match || !only_once) BEGIN
              PATCH_IF "%match_function%" STRING_COMPARE "" BEGIN
                READ_ASCII 0x0 data_temp (BUFFER_LENGTH)  // we do this to avoid side-effects
                INNER_PATCH "%data_temp%" BEGIN
                    LPF "%match_function%" RET v_func=value END
                END
              END ELSE BEGIN
                SET v_func=1
              END
              PATCH_IF
             ( INDEX_BUFFER ("%match%")>=0     AND
               INDEX_BUFFER ("%match1%")>=0    AND
               INDEX_BUFFER ("%match2%")>=0    AND
               INDEX_BUFFER ("%match3%")>=0    AND
               INDEX_BUFFER ("%match4%")>=0    AND
               INDEX_BUFFER ("%match5%")>=0    AND
               v_func=1
              )
              BEGIN
                SET proceed=1
              END
             END
             PATCH_IF proceed BEGIN
                 SET found_match=1
                 PATCH_MATCH "%type%" WITH
                 alter BEGIN
                     PATCH_IF "%patch%" STRING_COMPARE "" BEGIN LPF "%patch%" END END
                     PATCH_IF "%swap_out%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out%" "%swap_in%" END
                     PATCH_IF "%swap_out1%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out1%" "%swap_in1%" END
                     PATCH_IF "%swap_out2%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out2%" "%swap_in2%" END
                     PATCH_IF "%swap_out3%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out3%" "%swap_in3%" END
                     PATCH_IF "%swap_out4%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out4%" "%swap_in4%" END
                     PATCH_IF "%swap_out5%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out5%" "%swap_in5%" END
                 END
                 clone BEGIN
                    READ_ASCII 0x0 data2 (BUFFER_LENGTH)
                    INNER_PATCH_SAVE data2 "%data2%" BEGIN
                       PATCH_IF "%patch%" STRING_COMPARE "" BEGIN LPF "%patch%" END END
                       PATCH_IF "%swap_out%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out%" "%swap_in%" END
                       PATCH_IF "%swap_out1%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out1%" "%swap_in1%" END
                       PATCH_IF "%swap_out2%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out2%" "%swap_in2%" END
                       PATCH_IF "%swap_out3%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out3%" "%swap_in3%" END
                       PATCH_IF "%swap_out4%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out4%" "%swap_in4%" END
                       PATCH_IF "%swap_out5%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%swap_out5%" "%swap_in5%" END
                    END
                    PATCH_IF "%patch_original%" STRING_COMPARE "" BEGIN LPF "%patch_original%" END END
                    PATCH_IF "%original_swap_out%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%original_swap_out%" "%original_swap_in%" END
                    PATCH_IF "%original_swap_out1%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%original_swap_out1%" "%original_swap_in1%" END
                    PATCH_IF "%original_swap_out2%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%original_swap_out2%" "%original_swap_in2%" END
                    PATCH_IF "%original_swap_out3%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%original_swap_out3%" "%original_swap_in3%" END
                    PATCH_IF "%original_swap_out4%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%original_swap_out4%" "%original_swap_in4%" END
                    PATCH_IF "%original_swap_out5%" STRING_COMPARE "" BEGIN REPLACE_TEXTUALLY "%original_swap_out5%" "%original_swap_in5%" END
                    PATCH_IF insert_above BEGIN
                       SET insert_point=0
                    END ELSE BEGIN
                       SET insert_point=BUFFER_LENGTH
                    END
                    INSERT_BYTES insert_point (STRING_LENGTH "%data2%")
                    WRITE_ASCIIE insert_point "%data2%"
                 END
                 delete BEGIN
                    DELETE_BYTES 0x0 BUFFER_LENGTH
                 END
                 insert BEGIN
                    PATCH_IF replace BEGIN
                       DELETE_BYTES 0x0 BUFFER_LENGTH
                    END
                    PATCH_IF insert_above BEGIN
                       SET insert_point=0
                    END ELSE BEGIN
                       SET insert_point=BUFFER_LENGTH
                    END
                    INSERT_BYTES insert_point (STRING_LENGTH "%internal_insert_data%")
                    WRITE_ASCIIE insert_point "%internal_insert_data%"
                 END
                 DEFAULT
                    PATCH_FAIL "internal error in ALTER_SCRIPT suite"
                 END
             END
          END
          SPRINT new_script "%new_script%%data%"
          SET start=INDEX_BUFFER("CR")
     END
     DELETE_BYTES 0x0 BUFFER_LENGTH
     INNER_PATCH_SAVE new_script "%new_script%" BEGIN
        PATCH_IF recompile BEGIN
           COMPILE_BAF_TO_BCS
        END
        SET new_length=BUFFER_LENGTH
     END
     INSERT_BYTES 0x0 new_length
     WRITE_ASCIIE 0x0 "%new_script%"
BUT_ONLY
END
```
</details>

**Comment by burner1024** [comment]
I just need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example): screenshot and text. That saves time and reduces amount of miscommunication errors.

Pushed an update, how about now?
![Captura de pantalla de 2019-09-14 19-35-45](https://user-images.githubusercontent.com/1279852/64908186-135bf200-d727-11e9-9b8c-7dd216d33210.png)

**Comment by 4Luke4** [comment]
> I just need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example): screenshot and text. That saves time and reduces amount of miscommunication errors.

Got it.

So, now there are problems with variable identifiers when launching a function:
After your update
<img width="278" alt="Next update" src="https://user-images.githubusercontent.com/39967126/64909153-ccf79a80-d708-11e9-917e-0ae1419ab35f.png">
v1.0.9
<img width="267" alt="v1 0 9" src="https://user-images.githubusercontent.com/39967126/64909159-dd0f7a00-d708-11e9-84db-e04821b989ad.png">

**Comment by burner1024** [comment]
What about now?

**Comment by 4Luke4** [comment]
> What about now?

Nope, sorry....

<img width="947" alt="Broken – again" src="https://user-images.githubusercontent.com/39967126/64945833-c20c4980-d871-11e9-9045-db7f63b0a186.png">

**Comment by burner1024** [comment]
Screenshot _and_ text, please.

**Comment by 4Luke4** [comment]
> Screenshot _and_ text, please.

<img width="948" alt="Schermata 2019-09-16 alle 16 14 03" src="https://user-images.githubusercontent.com/39967126/64965415-41634280-d89d-11e9-9e3c-dbe068b0d351.png">

**Comment by burner1024** [comment]
Text, please.

**Comment by 4Luke4** [comment]
> Text, please.

```
LAF DELETE_SCRIPT_BLOCK
STR_VAR
	script = ~GTSUM00~
	match = EVAL "RESPONSE #100[%WNL%%LNL%%MNL%]*END"
END

ACTION_IF	!FILE_EXISTS_IN_GAME	~GTGOBRSU.cre~	BEGIN
	CREATE	"CRE"	"GTGOBRSU"
		SAY	NAME1	@1
		SAY	NAME2	@1
		WRITE_LONG	0x0010	BIT1	// No corpse
		WRITE_SHORT	0x0024	30	// Current HP
		WRITE_SHORT	0x0026	30	// Maximum HP
		WRITE_LONG	0x0028	IDS_OF_SYMBOL	(~ANIMATE~ ~GOBLIN_BOW_ELITE~)
END
```

**Comment by burner1024** [comment]
And now?

**Comment by 4Luke4** [comment]
> And now?

Everything seems to be OK now but a minor issue: you may wanna use different colors for tra references (e.g. `@3`) and `%variables%` (or vars declaration)....

<img width="529" alt="Different colors" src="https://user-images.githubusercontent.com/39967126/65131611-d2522f00-d9ff-11e9-9c0f-d4d904af6e9d.png">

**Comment by burner1024** [comment]
[There are only so many colors](https://forums.bgforge.net/viewtopic.php?f=35&t=139). If you have a specific suggestion, I'm listening. Theme editor linked in the topic will help you get an idea about what's possible.

**Comment by burner1024** [comment]
If there are no suggestions, I guess I'm closing this.

**Comment by 4Luke4** [comment]
> If there are no suggestions, I guess I'm closing this.

OK, feel free to close it, I'll think about that for the next update....

Before I forget, there's a minor issue with comments and `DEFINE_PATCH_FUNCTION` (or `DEFINE_ACTION_FUNCTION`)

<img width="695" alt="Schermata 2019-09-19 alle 16 28 12" src="https://user-images.githubusercontent.com/39967126/65310924-99e15b00-db8f-11e9-9489-eb73dbde3fc0.png">

**Comment by burner1024** [comment]
Fixed that as well. New release will be up shortly.

**Comment by 4Luke4** [comment]
> Fixed that as well. New release will be up shortly.

Sorry, don't forget about numerical constants too (have a look at the same screenshot...)

**Comment by burner1024** [comment]
damn, it's back to square one
