### ISSUE TITLE
Add support for 2DA files

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#15]
Pretty much what the title says.

I'd like to have `.2da` syntax highlighting (so that they don't look like plain text files). Something similar to what you've recently done with `.tra` files.

**Comment by burner1024** [comment]
How's this look
![Captura de pantalla de 2019-10-24 20-30-39](https://user-images.githubusercontent.com/1279852/67490344-45089700-f69d-11e9-9d7c-ed2ce2ed90cf.png)

**Comment by 4Luke4** [comment]
OK, it looks fine.
