### ISSUE TITLE
[WeiDU] VS Code console should not throw an error every time you write a trigger/action

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#2]
OK, this is rather odd, but what can you tell me of this?

<img width="1153" alt="console error" src="https://user-images.githubusercontent.com/39967126/50552307-c5828500-0c90-11e9-89b5-4b7251590bc4.png">

**Comment by burner1024** [comment]
Yes it shoudn't. Can't look into this without steps to reproduce, though.

**Comment by burner1024** [comment]
Found it. We'll have proper signatures later, for now it's just disabled for d/baf (well, and tp2 too).
