### ISSUE TITLE
[WeiDU, feature request]Add support for SSL/SLB files

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#20]
@burner1024 

Since we're speaking of `BAF` files, I must confess that I rarely use them – I prefer to code scripts in [SSL](https://www.gibberlings3.net/forums/topic/13725-coding-scripts-in-ssl-some-lessons/), it's much more compact and versatile.

So, my question is: what do you think about adding support for this format?

**Comment by burner1024** [comment]
Yes, I had that in mind since the beginning. It's just that no one asked, and since there's no demand - there's no supply.
I didn't use SSL myself, so I'm going to need formal syntax description. Full, with all the words. And some samples. And I don't know what SLB is.

Also, there's a particular issue of nerds being really creative with names:
- DavidW's `Stratagems Scripting Language` = `.ssl`
- [Fallout](https://falloutmods.fandom.com/wiki/Fallout_1_and_Fallout_2_scripting_-_commands,_reference,_tutorials) `Star-Trek Scripting Language` = `.ssl`

Seriously?
Although, `MultiLanguage Server` = `MLS` :roll_eyes: who am I to complain. Will need to add an extra setting or something to distinguish.

**Comment by 4Luke4** [comment]
>I didn't use SSL myself, so I'm going to need formal syntax description. Full, with all the words. And some samples. And I don't know what SLB is.

Well, you could start by looking at the underlying Perl source code [here](https://github.com/Gibberlings3/SwordCoastStratagems/blob/master/stratagems/ssl/ssl.pl).
The `ssl` files are the actual code, whereas the `slb` files are "library files" containing common data.
I can give you lots of code snippets but first you'd better get familiar with its syntax (shouldn't be too hard for you....)

**Comment by burner1024** [comment]
I don't see how perl code would help. I think it's going to be a fool's errand to work on implementing it without having any first hand experience, sorry. So if syntax tree isn't described by someone who works with SSL often, it'll have to wait until I actually use it somewhere.

**Comment by 4Luke4** [comment]
> I don't see how perl code would help. I think it's going to be a fool's errand to work on implementing it without having any first hand experience, sorry. So if syntax tree isn't described by someone who works with SSL often, it'll have to wait until I actually use it somewhere.

I see.
If that's the case, then I think I could try to write down the related context-free grammar with the help of some code samples... I've been using it for quite some time, so I'd like to try...

**Comment by burner1024** [comment]
That'd be great. The important thing is to define standard blocks, actual code words don't matter so much.

**Comment by 4Luke4** [comment]
@burner1024 

Since any `BAF` block is a valid `SSL` (but not `SLB`!) block, you could start by implementing that....

**Comment by burner1024** [comment]
No point, starting from more specific blocks might lead to throwing it all away later. Need to start from the root.

**Comment by 4Luke4** [comment]
I see.

So, just to give you an idea (`SSL` format):
```
BEGIN_ACTION_DEFINITION
	Name(AttackReevaluate)
	TRIGGER
		Allegiance(Myself,EVILCUTOFF)
	ACTION
		RESPONSE #scsprob1
			AttackReevaluate(scstarget,scsargument1)
END

IF TRIGGER
	TargetBlock(EVILCUTOFFsInOrder)
	TriggerBlock(MainhandWeaponUsable)
	StateCheck(scstarget,0x9)
	!StateCheck(scstarget,STATE_REALLY_DEAD)
	Range(scstarget,4)
THEN DO
	Action(AttackReevaluate,45)
END
```

`TargetBlock`s and `TriggerBlock`s are defined in a separate `SLB` file:
```
TARGET=EVILCUTOFFsInOrder
	[EVILCUTOFF]
	SecondNearest([EVILCUTOFF])
	ThirdNearest([EVILCUTOFF])
	FourthNearest([EVILCUTOFF])
	FifthNearest([EVILCUTOFF])
	SixthNearest([EVILCUTOFF])

TRIGGER=MainhandWeaponUsable
	WeaponEffectiveVs(scstarget,MAINHAND)
	WeaponCanDamage(scstarget,MAINHAND)
```

`scstarget` will compile as `[EVILCUTOFF]`, `SecondNearest([EVILCUTOFF])`, etc. up to `SixthNearest([EVILCUTOFF])`. As you can see, that's pretty powerful...

**Comment by burner1024** [comment]
I see. For the purposes of highlighting doesn't really matter how it compiles, though.
SSL blocks looks simple enough. The problem with SLB is that I don't see what marker to detect as the end of the block (both TARGET and TRIGGER)

**Comment by 4Luke4** [comment]
> I see. For the purposes of highlighting doesn't really matter how it compiles, though.

Yes, you're right, I specified it for clarification purposes...

> The problem with SLB is that I don't see what marker to detect as the end of the block (both TARGET and TRIGGER)

[As far as I know](https://github.com/Gibberlings3/SwordCoastStratagems/blob/master/stratagems/ssl/library.slb), there's no marker to detect the end of both a `TARGET` block and a `TRIGGER` block...

**Comment by 4Luke4** [comment]
Next: on top of standard BAF operators, you need to add `&` and `|`:
`TriggerBlock(IsTargetableWithSpells|MR50|SINecromancy|MinorGlobe)`
`ConditionalTargetBlock(EVILCUTOFFsInOrderShort;OR(5)&Class(scstarget,MAGE_ALL)&Class(scstarget,CLERIC_ALL)&Class(scstarget,DRUID_ALL)&Class(scstarget,BARD_ALL)&Class(scstarget,SHAMAN))`

**Comment by 4Luke4** [comment]
Additional `SSL` keywords:
```
INCLUDE FILE("%path_to_ssl_file%")
Combine()
ActionCondition("%action_name%","%list_of_arguments%") // According to the underlying Perl code, this is identical to standard 'Action()'s – probably it's not been implemented yet...
BEGIN LOOP ... END LOOP
VARIABLE
```

**Comment by 4Luke4** [comment]
`SLB` format: there are four main keywords: `TRIGGER`, `TRIGGER_REPLACE`, `TARGET`, and `TARGET_REPLACE`. Basically, each `TRIGGER` block is a collection of `BAF` triggers, whereas each `TARGET` block is a collection of [script objects](https://gibberlings3.github.io/iesdp/files/ids/bgee/object.htm).

```
TRIGGER=IsSpellcaster
	OR(5)
		Class(scstarget,MAGE_ALL)
		Class(scstarget,CLERIC_ALL)
		Class(scstarget,DRUID_ALL)
		Class(scstarget,BARD_ALL)
		Class(scstarget,SHAMAN)

TRIGGER=AoEIceStorm
		OR(3)
		   NextTriggerObject(scstarget)Range(NearestAllyOf(Myself),15)
		   NumInParty(1)
		   GlobalTimerNotExpired("targetcompromise","LOCALS")
		OR(4)
		   NextTriggerObject(scstarget)!Range(NearestEnemyOfType([0.HUMANOID]),22)
		   NextTriggerObject(scstarget)CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTCOLD)
		   NextTriggerObject(scstarget)CheckStatGT(NearestEnemyOfType([0.HUMANOID]),59,RESISTMAGIC)
		   NextTriggerObject(scstarget)Race(NearestEnemyOfType([0.HUMANOID]),RAKSHASA)

TARGET=Beholders
	[0.0.BEHOLDER]
	SecondNearest([0.0.BEHOLDER])
	ThirdNearest([0.0.BEHOLDER])
	FourthNearest([0.0.BEHOLDER])
	FifthNearest([0.0.BEHOLDER])

TARGET=EnemySpellcasters
	[EVILCUTOFF.0.0.MAGE_ALL]
	SecondNearest([EVILCUTOFF.0.0.MAGE_ALL])
	ThirdNearest([EVILCUTOFF.0.0.MAGE_ALL])
	[EVILCUTOFF.0.0.BARD]
	[EVILCUTOFF.0.0.CLERIC_ALL]
	[EVILCUTOFF.0.0.DRUID_ALL]
	SecondNearest([EVILCUTOFF.0.0.CLERIC_ALL])
	SecondNearest([EVILCUTOFF.0.0.DRUID_ALL])
```

**Comment by burner1024** [comment]
I added basic hightlighting for both types, you should be able to try them in development mode. I know it's not perfect yet, but the bulk is there.
You might need to [set files associations](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file) to have `.ssl` detected as WeiDU variant:
```json
"files.associations": {
  "*.ssl": "weidu-ssl"
}
```

Feel free to try and report any issues, as usual, with screenshots. Well, you can try to handle them yourself, too. Syntax definition is basically a bunch of regexes including each other, and if you know WeiDU, you should be familiar with regexes as well. (After fixing yml, run `scripts/syntaxes_to_json.sh`).

**Comment by 4Luke4** [comment]
@burner1024 

Looks good, good job.

There's a color conflict with the keyword `KIT`: as you know, this is both a script trigger and a STAT. The problem is that it gets highlighted as a STAT when used as a script trigger...

<img width="377" alt="KIT" src="https://user-images.githubusercontent.com/39967126/69956256-ca366580-14ff-11ea-924b-36b8d25505cd.png">

**Comment by burner1024** [comment]
Without delving too deep, we could make it case sensitive and resolve the conflict that way.

**Comment by 4Luke4** [comment]
> Without delving too deep, we could make it case sensitive and resolve the conflict that way.

Yes, that sounds more robust.

In so doing, you'll be able to distinguish, say, the TRIGGER block _MinorGlobe_ from the STAT `MINORGLOBE`...

**Comment by burner1024** [comment]
I don't see stat MINORGLOBE.
Maybe it's better to use case sensitive names for everything. The reason they were added as case insensitive is because the compiler doesn't care. I don't the extenstion making a gentle push to better code style, though.
Anyway, such a change is trivial, so I'll leave it to whoever wants to do that.

**Comment by 4Luke4** [comment]
> I don't see stat `MINORGLOBE`.

It's STAT#64.

**Comment by 4Luke4** [comment]
> > I don't see stat `MINORGLOBE`.
> 
> It's STAT#64.

Look [here](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/611af76061d6a1beb472f731531c3ed0e626c794/syntaxes/weidu.baf.tmLanguage.yml#L2148).

**Comment by burner1024** [comment]
Right, it's the other way around, it's in the stat, but not in triggers.

**Comment by burner1024** [comment]
OK then, if there isn't any obvious issue, I guess this may be closed.
