### ISSUE TITLE
[WeiDU, .tra]Syntax Highlighting should highlight %variable% references appropriately

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#21]
Unlike `.tp2` files, `%variable%` references are not highlighted appropriately (i.e., you cannot distinguish them from the content of the string).

<img width="823" alt="TRA – %variable%" src="https://user-images.githubusercontent.com/39967126/69956870-83e20600-1501-11ea-9995-27ad0649a5f7.png">

**Comment by 4Luke4** [comment]
@burner1024 

Guess you should reopen this issue.

There's a problem with the array construct:
`TEXT_SPRINT $patchITM(%spl%) ~%itm%~`

<img width="491" alt="array" src="https://user-images.githubusercontent.com/39967126/79591989-9d16d800-80d9-11ea-822c-7f732854503b.png">

**Comment by burner1024** [comment]
But this one is about `tra`. Please feel free to re-open the right one, or file a new one.
