### ISSUE TITLE
[highlighting][ssl] "procedure" missing colors when "begin" is on next line

### ISSUE THREAD

**Issue by wipe2238** [BGforgeNet/VScode-BGforge-MLS#27]
![obraz](https://user-images.githubusercontent.com/1433300/73586170-96e56800-44a9-11ea-944d-4797c1528089.png)

First `procedure` is missing colors as long as `begin` is on next line; if it's moved to same line as `procedure`, colors are set properly. Pretty minor and very easy to miss if using only one style for a whole file.

Would be nice if highlight could work same way no matter of `begin` position.

**Comment by burner1024** [comment]
Right, I always use the same line, so it went unnoticed.
![Captura de pantalla de 2020-02-01 14-14-38](https://user-images.githubusercontent.com/1279852/73588578-6cbd9580-44fd-11ea-857a-3ccb34ab59e9.png)
