### ISSUE TITLE
[highlighting] SSL 'call' colorizing incosistency

### ISSUE THREAD

**Issue by wipe2238** [BGforgeNet/VScode-BGforge-MLS#29]
- procedure name is not colorized when using `call proc();` syntax
  skipping `()` and using `call proc;` syntax works correctly
- procedure name is not colorized if there's at least 1 whitespace between name and `(`
  engine/sfall functions does not have that problem, and are colorized correctly

Both are edge cases; first probably overlooked as scripts i checked simply skip `()` - for me it's a muscle memory due to messing with C-like langs :} Second can be spotted only if someone wants to write pretty code and align arguments at same position when using block of procs with different names length; haven't seen anything like that in regular mods either.

![image](https://user-images.githubusercontent.com/1433300/75881161-d98abf00-5e1e-11ea-9857-f10ebdaa8933.png)

**Comment by burner1024** [comment]
Cool, I got this. But future, please paste text too, to make sure I can reproduce it.

**Comment by burner1024** [comment]
![Captura de pantalla de 2020-03-04 21-34-45](https://user-images.githubusercontent.com/1279852/75889964-43778880-5e60-11ea-854c-c3f8e4097554.png)

Will release sometime soon, need to take care of other things too.
