### ISSUE TITLE
[WeiDU] Syntax Highlighting should highlight %variable% references appropriately

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/VScode-BGforge-MLS#30]
When using the array construct, Syntax Highlighting should highlight `%variable%` references appropriately.

Example:
`TEXT_SPRINT $patchITM(%spl%) ~%itm%~`

<img width="491" alt="array" src="https://user-images.githubusercontent.com/39967126/79592994-1662fa80-80db-11ea-9ddd-db172979abce.png">

**Comment by burner1024** [comment]
Here's a sample, what do you think
![Captura de pantalla de 2020-04-18 14-02-36](https://user-images.githubusercontent.com/1279852/79630650-4c58bb00-817d-11ea-87b9-75e997dd57ae.png)

**Comment by 4Luke4** [comment]
OK, looks fine.
