### ISSUE TITLE
[WeiDU, .slb] Syntax Highlighting should highlight TARGET/TRIGGER names appropriately

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/VScode-BGforge-MLS#31]
Syntax Highlighting should be consistent when highlighting TARGET/TRIGGER names that contain `-` characters.

Example:
`TARGET=EVILCUTOFF-FIGHTER_ALLsInOrderShort`

<img width="512" alt="- character" src="https://user-images.githubusercontent.com/39967126/79603444-a52c4300-80ec-11ea-9f6b-abd8bbeda28e.png">

**Comment by burner1024** [comment]
![Captura de pantalla de 2020-04-18 14-07-31](https://user-images.githubusercontent.com/1279852/79630727-f59fb100-817d-11ea-8346-e58b1a5bee3c.png)

should be good now

**Comment by 4Luke4** [comment]
@burner1024 

You might want to check `tpa` and `tph` files too...

**Comment by burner1024** [comment]
They don't have TARGET, and I don't see any issues currently.

**Comment by 4Luke4** [comment]
@burner1024 

Please, fix this issue for `SSL` files too...

**Comment by burner1024** [comment]
Do they use TARGET keyword too?

**Comment by 4Luke4** [comment]
> Do they use TARGET keyword too?

Yep.

`TargetBlock(PC-FIGHTER_ALLsInOrderShort)`

**Comment by burner1024** [comment]
Well, this code is not coloring for me, whether there's a dash or not.
Please report the full use case in a separate issue.
