### ISSUE TITLE
[WeiDU, .tpa/tph] Syntax Highlighting should handle "-" characters and string delimiters appropriately

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/VScode-BGforge-MLS#32]
If you combine `-` characters and string delimiters `" // or ~`, then everything is messed up.

Example code:
```
DEFINE_ACTION_FUNCTION ~demi-shadow_monsters~
BEGIN
	ACTION_IF (VARIABLE_IS_SET ~WIZARD_DEMI_SHADOW_MONSTERS~) BEGIN
```

<img width="1146" alt="~ + -" src="https://user-images.githubusercontent.com/39967126/80204031-6cc6c080-8628-11ea-8657-e7cf16d0934e.png">

**Comment by burner1024** [comment]
![Captura de pantalla de 2020-04-24 17-47-57](https://user-images.githubusercontent.com/1279852/80204820-c1cbfc00-8653-11ea-91ee-18bd6eba37c6.png)

**Comment by 4Luke4** [comment]
@burner1024 

As you can see, the second `~` in "demi-shadow_monsters" is highlighted in green (should be red...)

**Comment by burner1024** [comment]
ahh, missed that

**Comment by burner1024** [comment]
![Captura de pantalla de 2020-04-24 18-24-18](https://user-images.githubusercontent.com/1279852/80207700-d6f75980-8658-11ea-8b36-b1e21e2e870f.png)
