### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Dredd893** [BGforgeNet/VScode-BGforge-MLS#33]
https://forums.beamdog.com/discussion/comment/1082197/#Comment_1082197

Hello, was checking this topic. Any chance of adding the feature Arthas asked for? I would be interested too.

**Comment by burner1024** [comment]
This is a wrong repo, you need [TnT](https://github.com/BGforgeNet/bg2-tweaks-and-tricks) one. Please open an issue there and describe your request.
