### ISSUE TITLE
[WeiDU] Documentation does not show up

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/VScode-BGforge-MLS#34]
After the last update (v1.9.0), online documentation no longer shows up upon hovering mouse cursor over the various keywords...

**Comment by burner1024** [comment]
Confirmed, lookin into it.

**Comment by burner1024** [comment]
I rolled back some changes, should work now.
This will have to be addressed at some point, as MS [deprecated](https://www.npmjs.com/package/vscode) vscode module, but I don't have time now to deal with this properly.
