### ISSUE TITLE
[WeiDU, .ssl] Syntax Highlighting should highlight 'TargetBlock/TriggerBlock' names appropriately

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/VScode-BGforge-MLS#35]
Syntax Highlighting should be consistent when highlighting `TargetBlock/TriggerBlock` names that contain `- // hyphen` characters.

Example:
```
TargetBlock(PC-FIGHTER_ALLsInOrderShort&GOODCUTOFF-FIGHTER_ALLsInOrderShort)
TriggerBlock(PC-test)
```

<img width="928" alt="SSL" src="https://user-images.githubusercontent.com/39967126/82034628-bc842f00-969e-11ea-9268-7bc219f2a7d8.png">

**Comment by burner1024** [comment]
This is what I get
![Captura de pantalla de 2020-05-15 16-26-18](https://user-images.githubusercontent.com/1279852/82034801-df2b3d80-96c8-11ea-898e-4024a3dec583.png)

Which version do you use?

**Comment by 4Luke4** [comment]
I'm using `v1.9.1`.

That's invalid syntax though. It should be:
```
IF TRIGGER
  TargetBlock(PC-FIGHTER_ALLsInOrderShort&GOODCUTOFF-FIGHTER_ALLsInOrderShort)
  TriggerBlock(PC-test)
THEN DO
  Action(Test)
END
```

**Comment by burner1024** [comment]
So what do you expect to see? No coloring for names?

**Comment by 4Luke4** [comment]
> So what do you expect to see? No coloring for names?

Yeah, that's probably better... This issue arises every time you mix WeiDU constants (e.g. PC) with some other text (+ the hyphen character...)

**Comment by burner1024** [comment]
![Captura de pantalla de 2020-05-15 17-33-13](https://user-images.githubusercontent.com/1279852/82041416-587b5e00-96d2-11ea-9435-c4e2f13bcc1d.png)
