### ISSUE TITLE
Indicate field size somehow

### ISSUE THREAD

**Issue by burner1024** [BGforgeNet/VScode-BGforge-MLS#36]
It would be great to have some visual indicator of the field size for [IElib](https://github.com/BGforgeNet/BGforge-MLS-IElib) constants, to know when to use `READ_BYTE` vs `READ_SHORT`, etc. Maybe not for all types, but at least for the common ones.

Some options:
1. Append a corresponding suffix (_b, _w, _dw, etc) in IElib itself. A bit clunky and the names are long already. But simple enough and works.
2. Indicate in the tooltip. Not as visible, and will require much larger rewrite of how IElib works.
3. Some scopes in [Monokai](https://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai) are still unused. There's underlining, italic, etc. However, using those for constants would not be in line with other languages, and somewhat confusing because of that.
4. Make a custom Monokai fork and ship it with the extension and let users know to enable it. Not user-friendly, and likely a large maintenance burden.
5. Maybe Monokai supports some kind of customizaion/overrides? That way, it could be extended to support more scopes with different indicators.
6. Check if there are any other themes, (preferably Monokai-based), that allow distinguishing between different constant types.
7. Anything else?

Any option would require changes to IElib, though, because the information about type has to come from _somewhere_.

**Comment by burner1024** [comment]
Ok, so unfortunately themes don't support inheritance. On the bright side, however, it turns out that a theme is [just a bunch of css stuffed into json](https://github.com/microsoft/vscode/blob/master/extensions/theme-monokai/themes/monokai-color-theme.json).
Therefore, it wouldn't be too hard to make a custom one. Obviously, I don't like the idea of locking to one theme. But in fact, anyone who want can customize whatever they want and submit a pull. And I don't see any other way to improve display.

A glimpse of things to come:
![Captura de pantalla de 2020-07-26 01-53-11](https://user-images.githubusercontent.com/1279852/88464166-c9b16b80-cee2-11ea-8bd5-8135be276514.png)

Bundling a custom theme will allow to increase the number of scopes and customize them however we need. But the actual meat will still have to be handled, for weidu syntax and ielib as well - the scopes won't mark themselves.
@4Luke4 what do you think?

**Comment by 4Luke4** [comment]
> @4Luke4 what do you think?

OK, sounds good, guess we can try...

**Comment by burner1024** [comment]
Any suggestions on actual styling?
For now I think about the following types:
- byte
- word
- dword
- bit (flag)
- resref
- unknown (default for any other types)

We got bold, italic and underline, that's 8 variants. I'd prefer to keep color the same for constants. Default should be normal style.
Not sure how to make byte-word-dword succession intuitive.

**Comment by 4Luke4** [comment]
> For now I think about the following types:
> 
> * byte
> * word
> * dword
> * bit (flag)
> * resref
> * unknown (default for any other types)

There's also:
* reverse long (kit field of CRE files)

**Comment by burner1024** [comment]
Well, that's pretty specific, I don't think it's possible to cover every case.

**Comment by burner1024** [comment]
btw, I pushed some changes: differentiating actions vs patches, and some improvements for functions display. Try it out, for best results select BGforge Monokai theme in development host.
