### ISSUE TITLE
Steals c/c++ header file association

### ISSUE THREAD

**Issue by flamewing** [BGforgeNet/VScode-BGforge-MLS#37]
1. Observed behavior. When installed, it configures "*.h" files away from C/C++.
2. Expected behavior. It should not do that.

**Comment by burner1024** [comment]
It doesn't configure them away, just registers for handling them (too). I think VScode has some weight-based algorithm for deciding which language id is to be used, but I can't find the link now.
Anyway, if you want them to go back to C++ variant, you can configure VScode the same way it's done for [SSL](https://github.com/BGforgeNet/VScode-BGforge-MLS#ssl).
