### ISSUE TITLE
Autocompletion: weidu built-in macro and functions

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#4]
The following **PATCH** functions are missing:

- `ADD_ITEM_EQEFFECT`
- `ADD_ITEM_EFFECT`
- `ADD_SPELL_EFFECT`
- `ADD_SPELL_CFEFFECT`

**Comment by burner1024** [comment]
It's easy to [add](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/server/out/weidu.completion.yml) the missing stuff, so pulls are welcome (...or I'll fix it myself when I get to this).

**Comment by burner1024** [comment]
In fact, all built-in functions and macro need be added, not just the mentioned 4.

**Comment by 4Luke4** [comment]
All built-in macros and functions have been added with the latest release (v1.0.9)
