### ISSUE TITLE
Separate bgforge.weidu.path by OS and default values

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/VScode-BGforge-MLS#40]
Hi,

can you separate bgforge.weidu.path by OS? Like this:
```
bgforge.weidu.path.win
bgforge.weidu.path.mac
bgforge.weidu.path.lin
```
This would also allow for having `weidu.exe` as the default value for Windows OS, `weidu` for mac/lin. The additional improvement by implementing this is that extension would work out-of-the-box if the weidu.exe is added to system `PATH`.

**Comment by burner1024** [comment]
I don't think it's a good idea to have 3 settings instead of one.
Taking it from PATH is not related to having multiple settings and can be done separately.
In fact, I considered just shipping weidu with the extension instead of using a setting, but the current situation is good enough for me and I haven't got any other feedback, so not sure if anyone even uses the feature.

**Comment by ALIENQuake** [comment]
VSCode has setting sync so when I switch OS, I keep the same extension, settings etc. But if I have one setting for the weidu path, I must constantly update it after switching OS. A similar solution is used for other cross-platform extensions, like PowerShell.

I think that shipping your own weidu is a good idea if you also keep the ability to providing your own binary for beta etc.
You would take the burden to update it with every new weidu release?

There is a danger: weidu is very often marked as a virus because it is packed with UPX. You could ask wisp to update his release script in order to provide uncompressed weidu binaries.

**Comment by burner1024** [comment]
And what... you switch OS often?

**Comment by ALIENQuake** [comment]
I'm switching VM's. If you don't want to provide 3 settings, please investigate loading it from `PATH` as default so we can test if providing only `weidu` will cath `weidu.exe` for Windows, ok?

**Comment by burner1024** [comment]
Try this.
Clone and use F5 to launch development version.

**Comment by burner1024** [comment]
In fact, I think even in current release you can simply set the setting to "weidu" and it'll likely work.

**Comment by ALIENQuake** [comment]
Using `weidu` works with the current version 😄
