### ISSUE TITLE
The variable name of ID-Kit-Main has two colors because of minus char.

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/VScode-BGforge-MLS#41]
1. ![image](https://user-images.githubusercontent.com/365255/107392488-039e3400-6afa-11eb-90fb-57f3a7bcf410.png)

2. The **variable** name of `ID-Kit-Main` has two colors because of minus char.
3. I think this and that should be colored as one color.

**Comment by burner1024** [comment]
When reporting, paste code along with screenshot.
