### ISSUE TITLE
Autocompletion should adjust itself after launching a PATCH/ACTION function

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/VScode-BGforge-MLS#5]
For example, it should suggest:

- `INT_VAR`
- `RET`
- `STR_VAR`
- `opcode`
- `parameter1`
- `parameter2`
- `target`
- `duration`
- `timing`
- `resource`
- `special`
- `savingthrow`
- `savebonus`
- `power`
- `match_opcode`
- `header_type`
- `match_resist_dispel`
- `check_globals`
- etc...........

**Comment by burner1024** [comment]
Did you have a chance to check the snippets yet?

**Comment by 4Luke4** [comment]
> Did you have a chance to check out the snippets yet?

No, not yet...

**Comment by burner1024** [comment]
Well, those are easy, so it's best to evaluate what can be done with them, and then move on to more complicated scenarios.

**Comment by 4Luke4** [comment]
> Well, those are easy, so it's best to evaluate what can be done with them, and then move on to more complicated scenarios.

Yeah, they do seem to be easy, I'll see what I can do...
To tell the truth, I'm much more interested into [SFO](https://github.com/BGforgeNet/VScode-BGforge-MLS/issues/26#issuecomment-579126516)... Did you manage to wrap your head around it? Guess we can either use it as it is or rewrite it from the ground up (what I'm currently trying to do, but it's not an easy task...)

**Comment by burner1024** [comment]
What exactly do you want from SFO? You can use it normally. If there's more to is, let's discuss in a separate issue.

**Comment by burner1024** [comment]
I'm going to close this, since I see very little interest.
