### ISSUE TITLE
Requsest - Publish to OpenVSX

### ISSUE THREAD

**Issue by afrothundaaaa** [BGforgeNet/VScode-BGforge-MLS#52]
Hello.

I am hoping to get this library via https://open-vsx.org registry.  I see that it is not published. I was hoping that this could be an additional repository to host your extension.

Information on publishing to open-vsx: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Thank you

**Comment by burner1024** [comment]
I'll look into that; meanwhile you can downoad vsix from releases.

**Comment by burner1024** [comment]
[There](https://open-vsx.org/extension/BGforge/bgforge-mls).

**Comment by afrothundaaaa** [comment]
You are a legend.  Thank you so much!
