### ISSUE TITLE
Version 2+ cannot compile SSL if the output path contains spaces

### ISSUE THREAD

**Issue by blackpaulillyria** [BGforgeNet/VScode-BGforge-MLS#58]
Hi, I installed the latest version and couldn't compile SSL file to a target path that contained space(s) in its name. For example `C:\My Scripts`

I had to downgrade to version 1.16.3 which works well with such paths.

**Comment by burner1024** [comment]
What do you mean by couldn't?

**Comment by burner1024** [comment]
Is there an error that you see?

**Comment by blackpaulillyria** [comment]
```
stdout: Warning: c:\My not found
Warning: Scripts\.tmp.ssl not found
Warning: -o not found
Warning: test.int not found
```

**Comment by burner1024** [comment]
Try [this build](https://github.com/BGforgeNet/VScode-BGforge-MLS/actions/runs/4057759819)

**Comment by blackpaulillyria** [comment]
Sorry, no luck. Still throws the same error

**Comment by burner1024** [comment]
Show screenshot.

**Comment by blackpaulillyria** [comment]
Here you go

![image](https://user-images.githubusercontent.com/58548291/215980981-bcd53385-5196-4d51-99ed-2e25effb8cc1.png)

**Comment by burner1024** [comment]
Try last build, see what it shows then.

**Comment by blackpaulillyria** [comment]
Hi, still no luck but I think we're getting closer to fixing it. I see you wrapped the output filename into quotes but not the .tmp.ssl path. If you wrap that path too, the problem would be gone.

![image](https://user-images.githubusercontent.com/58548291/216022291-b88408ad-0c29-45ec-a157-9a316e2f4500.png)

**Comment by burner1024** [comment]
Ah you got source with spaces.
Should work now.

**Comment by blackpaulillyria** [comment]
That's it, works perfectly! Thank you so much!
