### ISSUE TITLE
Autocompletion: weidu built-in constants

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#6]
Pretty much what the title states.
Autocompletion should suggest all the constants listed in section 15 (WeiDU constants) of the official documentation.

**Comment by burner1024** [comment]
This is easy to do, just need to add them to [weidu.completion.yml](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/server/out/weidu.completion.yml)

**Comment by 4Luke4** [comment]
> This is easy to do, just need to add them to [weidu.completion.yml](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/server/out/weidu.completion.yml)

They must be added under [.tp2 value](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/42d5aa32e2d0f7602522cf30f79e27502f8f35a1/server/out/weidu.completion.yml#L1424), right?

**Comment by burner1024** [comment]
Right. And the corresponding highlighting rules are [here](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/42d5aa32e2d0f7602522cf30f79e27502f8f35a1/syntaxes/weidu.tmLanguage.yml#L620), with most of these constants already in.

**Comment by 4Luke4** [comment]
@burner1024 
OK, I created a pull request for this. Please check and review it...

**Comment by burner1024** [comment]
Fixed with pull #7.
