### ISSUE TITLE
[SSL] Problems are shown at the wrong file

### ISSUE THREAD

**Issue by phobos2077** [BGforgeNet/VScode-BGforge-MLS#61]
### Screenshot
![image](https://user-images.githubusercontent.com/4744345/236577943-78983dd1-ac27-4e4f-a2c3-f7ac328f19e7.png)
![image](https://user-images.githubusercontent.com/4744345/236577985-7142a509-f9f1-4a7a-b0e6-394fb5d89c0e.png)
![image](https://user-images.githubusercontent.com/4744345/236578000-47e1a7a1-8da3-4527-99ba-02e92d130edc.png)

### What's wrong on screenshot
Based on compiler output, error is in the header, but plugin points to a random spot in ssl file instead.

#### compilertest.ssl
```
#include "compilertest.h"

procedure start begin
    display_msg("Hello world!!!");
end
```

#### compilertest.h
```
procedure ceil(variable v) begin
    return v
end
```

**Comment by burner1024** [comment]
Try the [build](https://github.com/BGforgeNet/VScode-BGforge-MLS/actions/runs/4900037187), should be working now.

**Comment by phobos2077** [comment]
Seems to work, thanks.

**Comment by phobos2077** [comment]
There's some kind of issue with file paths: 
![image](https://user-images.githubusercontent.com/4744345/236681695-5cfdf1ad-0ea3-4cd3-8ecf-ac83c58fe0b3.png)

It's like it concats 2 full paths together.

**Comment by phobos2077** [comment]
Also sometimes compiler prints error in the following format:
```
[Error] <Semantic> <command_extra.h>:14:19: Undefined symbol LONG_HAIR in factor
```
Which the plugin can't seem to understand:
![image](https://user-images.githubusercontent.com/4744345/236681912-8ac65a55-b51e-464c-ad40-b0e01d04b0e6.png)

**Comment by phobos2077** [comment]
Also the list of problems seem to pile up all the time when working on several scripts. Have to restart VSCode to even make sense of what's going on. Would be nice to be able to dismiss "problems" somehow. I guess it would be less of an issue if path issue is fixed.

**Comment by burner1024** [comment]
Need reproducible cases for issues.
Regarding dismissing, that's how VScode generally works with any language. Have to fix the issues or close the files to clear problems.

**Comment by phobos2077** [comment]
The never clear for me because VSCode shows all errors as "tmp.ssl" instead of actual script name. When I fix issues and recompile - they never go away.

**Comment by burner1024** [comment]
If it's the semantic thing, get the fix, otherwise open a new issue I guess.
