### ISSUE TITLE
[SSL] Can't parse symantic error output properly

### ISSUE THREAD

**Issue by phobos2077** [BGforgeNet/VScode-BGforge-MLS#62]
### Screenshot
![image](https://user-images.githubusercontent.com/4744345/236683532-b5c33ba9-3404-4242-b07d-ac19b27f6e28.png)

### What's wrong on screenshot
It shows path as "Semantic> <.tml.ssl" instead of actual script path.

### Code

```
variable x;
variable x;
```

**Comment by burner1024** [comment]
Should be working now.
