### ISSUE TITLE
.bgforge.yml is case sensitive for Fallout .msg vs .ssl files?

### ISSUE THREAD

**Issue by QuantumApprentice** [BGforgeNet/VScode-BGforge-MLS#64]
### Screenshot
![bgforge yml doesn't recognize different case](https://github.com/BGforgeNet/VScode-BGforge-MLS/assets/70798396/d7e9505e-fad2-49ff-b1ad-4c5a4ad64ac0)

### What's wrong on screenshot
It looks like the .msg file isn't recognized if its a different case, but for some reason changing the .ssl file to all lower case didn't fix the issue.
Where does bgforge look for the matching filename? and is it possible to configure it to be case insensitive?

### Code

```

```

**Comment by burner1024** [comment]
- It looks whereever you point it with the corresponding directive.
- No.
- Some details [here](https://forums.bgforge.net/viewtopic.php?f=35&t=385).
