### ISSUE TITLE
[WeiDU] Vars should be properly highlighted in "*.tra" files

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/VScode-BGforge-MLS#71]
`%vars%` are not highlighted as such in `tra` files (tested with theme BGforge Monokai).

That is actually odd since they seem to be properly included (i.e. `include: source.tp2.weidu#non-weidu-vars`), so what is missing...?

**Comment by 4Luke4** [comment]
![vars_tra](https://github.com/BGforgeNet/VScode-BGforge-MLS/assets/39967126/038dca43-9eb3-4240-9e29-82b07ba65c11)

**Comment by burner1024** [comment]
Why would they be highlighted in tra files? I don't think tra support vars.

**Comment by 4Luke4** [comment]
> Why would they be highlighted in tra files? I don't think tra support vars.

Yes, it supports them, just try...

**Comment by 4Luke4** [comment]
> Why would they be highlighted in tra files? I don't think tra support vars.

Example usage [here](https://github.com/Gibberlings3/ItemRevisions/blob/master/item_rev/languages/english/description_updates.tra).

**Comment by burner1024** [comment]
My eyes, my eyes!!

**Comment by 4Luke4** [comment]
> My eyes, my eyes!!

ok, so what is the issue?

**Comment by burner1024** [comment]
scope mismatch
