### ISSUE TITLE
Use parameters data from actual code when jsdoc is used

### ISSUE THREAD

**Issue by phobos2077** [BGforgeNet/VScode-BGforge-MLS#72]
### Screenshot
![изображение](https://github.com/BGforgeNet/VScode-BGforge-MLS/assets/4744345/d4f9c61e-d873-4b68-be0e-1c8a6c290567)

### What's wrong on screenshot
- If you add jsdoc comment but omit some arguments, they disappear from the argument list in the hint.
- If you have default value in code itself, it is not reflected in the hint, you have to duplicate this information in the jsdoc

### Code

```
/**
 * Adds one recipe item for a given crafted item, if it doesn't exist. If recipe is known, deletes the item.
 * 
 * @arg {int} schematicPid - PID of schematic item to create
 * @arg {int} probability - % probability of spawn, if conditions are met.
 */
procedure check_restock_craft_schematic(variable schematicPid, variable craftedItemPid, variable probability := 100) begin
end
```

**Comment by phobos2077** [comment]
Would also be nice to parse and display comment after `@ret`

**Comment by burner1024** [comment]
I don't like duplication.
But I also don't like mixing info from different sources. I think it can get too complicated for too little gain.
Need to think about it. Maybe make an exception for default values, but I definitely don't want to merge argument lists.
Although trusting just one source seems more reliable still.

For functions with return values, the description of those is usually the first thing in the body of the docstring. So, not sure if that's any benefit.

**Comment by phobos2077** [comment]
> But I also don't like mixing info from different sources. I think it can get too complicated for too little gain.

Simple idea: if there's not a single @arg in comment, then you just take data from code (and put any as type). Otherwise trust the @args. This should fix the common case where you just want to put some description without writing out every arg.


> For functions with return values, the description of those is usually the first thing in the body of the docstring. So, not sure if that's any benefit.

It's just a simple readability improvement - you see return value described after arguments, like it usually is in documentation.

**Comment by burner1024** [comment]
> It's just a simple readability improvement - you see return value described after arguments, like it usually is in documentation.

Usually... where? Because this is what I usually see
![Captura desde 2024-05-23 15-51-00](https://github.com/BGforgeNet/VScode-BGforge-MLS/assets/1279852/658f16e9-7a93-44a1-a78c-bc47bc53c5ab)

**Comment by burner1024** [comment]
For args, I think default form will do
![Captura desde 2024-05-23 16-32-52](https://github.com/BGforgeNet/VScode-BGforge-MLS/assets/1279852/63ef9f75-d434-4cef-a8f2-09400a85ed46)

**Comment by burner1024** [comment]
If there's nothing to add about ret, I guess that'll be all.

**Comment by phobos2077** [comment]
> If there's nothing to add about ret, I guess that'll be all.

I mean, it would still be useful to be able to describe return value. But it's not as critical.

**Comment by burner1024** [comment]
I showed how it's usually described in my experience.
If your experience differs, feel free to share.

**Comment by phobos2077** [comment]
> If your experience differs, feel free to share.

Well I come from C# background. There comments have a structure with return value having it's own tag that describes what is returned separately. 

As I said, it's not very important, but a feature you would expect when writing structured comments. Why args have comment but ret does not? Feels inconsistent.
