### ISSUE TITLE
[WeiDU] "Detail" should not be missing

### ISSUE THREAD

**Issue by 4Luke4** [BGforgeNet/vscode-bgforge-mls#8]
OK, latest version (v1.0.5) - I noticed that "detail" (from [weidu.completion.yml](https://github.com/BGforgeNet/vscode-bgforge-mls/blob/master/server/out/weidu.completion.yml)) no longer shows up upon hovering over a specific tp2-action/flag/whatever.

For instance, if you hover over `ACTION_IF`, then you'll only see its documentation but not the following => `ACTION_IF value THEN BEGIN TP2 Action list END [ ELSE BEGIN TP2 Action list END ]`

**Comment by burner1024** [comment]
Typos... Should be working now.
